---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.3.9-jdk-8}

inputs:
  - name: pipeline
  - name: version
outputs:
  - name: deploy-output

run:
  path: pipeline/tasks/cf-deploy.sh
