---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
  - name: pipeline-resource
  - name: version

run:
  path: pipeline-resource/ci/tasks/validate-version-updated.sh

